let contacts = JSON.parse(localStorage.getItem('myContacts') || '[]');
const save = () => localStorage.setItem('myContacts', JSON.stringify(contacts));
const safe = s => String(s || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials = name => name.split(' ').map(x => x[0]).slice(0, 2).join('').toUpperCase();
function render() { const q = document.getElementById('search').value.toLowerCase(); const list = contacts.filter(c => Object.values(c).join(' ').toLowerCase().includes(q)); document.getElementById('count').textContent = `${contacts.length} contact${contacts.length === 1 ? '' : 's'}`; document.getElementById('contacts').innerHTML = list.length ? list.map(c => `<article class="card"><div class="avatar">${initials(c.name)}</div><div class="name">${safe(c.name)}</div>${c.phone ? `<div class="info">📞 ${safe(c.phone)}</div>` : ''}${c.email ? `<div class="info">✉️ ${safe(c.email)}</div>` : ''}<div class="actions"><button onclick="editContact(${c.id})">Edit</button><button class="delete" onclick="deleteContact(${c.id})">Delete</button></div></article>`).join('') : '<div class="empty"><h2>No contacts yet</h2><p>Click “Add Contact” to save your first contact.</p></div>'; }
function openForm(contact) { document.getElementById('modal').classList.add('show'); document.getElementById('formTitle').textContent = contact ? 'Edit Contact' : 'Add Contact'; ['id','name','phone','email'].forEach(k => document.getElementById(k).value = contact?.[k] || ''); document.getElementById('name').focus(); }
function closeForm() { document.getElementById('modal').classList.remove('show'); }
function saveContact(event) { event.preventDefault(); const id = +document.getElementById('id').value; const data = { id: id || Date.now(), name: document.getElementById('name').value.trim(), phone: document.getElementById('phone').value.trim(), email: document.getElementById('email').value.trim() }; contacts = id ? contacts.map(c => c.id === id ? data : c) : [data, ...contacts]; save(); closeForm(); render(); }
function editContact(id) { openForm(contacts.find(c => c.id === id)); }
function deleteContact(id) { if (confirm('Delete this contact?')) { contacts = contacts.filter(c => c.id !== id); save(); render(); } }
document.getElementById('modal').onclick = event => { if (event.target.id === 'modal') closeForm(); }; render();
